---
# tasks file for createvmgcp

- name:                         create a disk
  gcp_compute_disk:
    name:                       disk-{{ instance_name }}
    size_gb:                    10
    source_image:               'projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts'
    zone:                       "{{ zone }}"
    project:                    "{{ gcp_project }}"
    auth_kind:                  "{{ gcp_cred_kind }}"
    service_account_file:       "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state:                      present
  register:                     disk

- name:                         create a network
  gcp_compute_network:
    name:                       'default'
    project:                    "{{ gcp_project }}"
    auth_kind:                  "{{ gcp_cred_kind }}"
    service_account_file:       "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state:                      present
  register:                     network

- name:                         Create an address
  gcp_compute_address:
    name:                       address-{{ instance_name }}
    region:                     "{{ region }}"
    project:                    "{{ gcp_project }}"
    auth_kind:                  "{{ gcp_cred_kind }}"
    service_account_file:       "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state:                      present
  register:                     address

- name:                         Create an instance
  gcp_compute_instance:
    state:                      present
    name:                       "{{instance_name}}"
    machine_type:               n1-standard-1
    disks:
      - auto_delete:            true
        boot:                   true
        source:                 "{{ disk }}"
    network_interfaces:
      - network:                "{{ network }}"
        access_configs:
          - name:               'External NAT'
            nat_ip:             "{{ address }}"
            type:               'ONE_TO_ONE_NAT'
    zone:                       "{{ zone }}"
    project:                    "{{ gcp_project }}"
    auth_kind:                  "{{ gcp_cred_kind }}"
    service_account_file:       "{{ gcp_cred_file }}"
    tags: 
      items: 
        - https-server
        - http-server
        - httpservers
    scopes:
      - https://www.googleapis.com/auth/compute
  register:                     instance

- name:                         Wait for SSH to come up
  wait_for:                     host={{ address.address }} port=22 delay=10 timeout=120

- name:                         Add host to groupname
  add_host:                     hostname={{ address.address }} groupname=new_instances
