---
# tasks file for roles/createec2aws/createwebservers.yml
- name: Get instances facts
  ec2_instance_facts:
    aws_access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    region: "{{ region }}"
  register: result

- name: Set haproxy_exists value
  set_fact:
    haproxy_exists: true
  with_items: "{{ result.instances }}"
  when: item.tags.type is defined and item.tags.type == "haproxy" 

- name:                   Block for create haproxy server if it doesnt exist
  block:
          
  - name:                 Provision instance(s)
    ec2:
      aws_access_key:     '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      aws_secret_key:     '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
      key_name:           "{{ key_name }}"
#     id:                 "{{ id_haproxy }}"
      group_id:           "{{ result_sec_group.group_id }}"
      image:              "{{ image }}"
      instance_type:      t2.micro
      region:             "{{ region }}"
      wait:               true
      instance_tags:
        type:             haproxy
      count:              1
    register:             ec2

  - name:                 Wait for SSH to come up
    wait_for:
      host:               "{{ item.public_dns_name }}"
      port:               22
      delay:              60
      timeout:            125
    with_items:           "{{ ec2.instances }}"
  
  - name:                 Refresh inventory to ensure new instances exist in inventory
    meta:                 refresh_inventory
  
  when:                   not haproxy_exists
