---
# tasks file for roles/createec2aws/createwebservers.yml
- name:                 Provision instance(s)
  ec2:
    aws_access_key:     '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key:     '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    key_name:           "{{ key_name }}"
    group_id:           "{{ result_sec_group.group_id }}"
    image:              "{{ image }}"
    instance_type:      t2.micro
    region:             "{{ region }}"
    wait:               true
    instance_tags:
      type:             webserver
    count:              "{{ number_ec2_machines }}"
  register:             ec2

- name:                 Wait for SSH to come up
  wait_for: 
    host:               "{{ item.public_dns_name }}"
    port:               22
    delay:              10
    timeout:            125
  with_items:           "{{ ec2.instances }}"

- name:                 Refresh inventory to ensure new instances exist in inventory
  meta:                 refresh_inventory

