---
# tasks file for roles/createec2aws
- name:                 Tasks for access to AWS
  include_tasks:        createaccess.yml

- name:                 Create or validate haproxy server
  include_tasks:        createhaproxy.yml

- name:                 Create webserver
  include_tasks:        createwebservers.yml

