---
# tasks file for roles/createec2aws
- name:                 Upload public key to AWS
  ec2_key:
    name:               "{{ key_name }}"
    key_material:       "{{ keymaterial }}"
    region:             "{{ region }}"
    aws_access_key:     '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key:     '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

- name:                 Create security group
  ec2_group:
    name:               "{{ sec_group }}"
    description:        "Sec group for app {{ id }}"
    region:             "{{ region }}"
    aws_access_key:     '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key:     '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    rules:
      - proto:          tcp
        ports:
          - 22
        cidr_ip:        0.0.0.0/0
        rule_desc:      allow all on ssh port
      - proto:          tcp
        ports:
          - 80
        cidr_ip:        0.0.0.0/0
        rule_desc:      allow all on http port
  register:             result_sec_group

- name:                 Provision instance(s)
  ec2:
    aws_access_key:     '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
    aws_secret_key:     '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
    key_name:           "{{ key_name }}"
    id:                 "{{ id }}"
    group_id:           "{{ result_sec_group.group_id }}"
    image:              "{{ image }}"
    instance_type:      t2.micro
    region:             "{{ region }}"
    wait:               true
    instance_tags:
      type:             webserver
    count:              1
  register:             ec2

- name:                 Wait for SSH to come up
  wait_for: 
    host:               "{{ item.public_dns_name }}"
    port:               22
    delay:              60
    timeout:            125
  with_items:           "{{ ec2.instances }}"

- name:                 Refresh inventory to ensure new instances exist in inventory
  meta:                 refresh_inventory

